"""
Builds a static, multi-page API documentation site for aat -- aat.core and
aat.english both included (aat's two-subpackage split is exactly what's
worth surfacing as its own pages here) -- using pdoc, straight from the
package's own docstrings and type hints.

Run from anywhere:
    python docs/build_docs.py

Requires pdoc (`pip install pdoc --break-system-packages`, or install the
'dev' extra: `pip install -e ".[dev]"`).

.github/workflows/docs.yml runs this same script on every push to `main`
and publishes docs/site/ to GitHub Pages -- see DEVELOPMENT.md. The output
directory (docs/site/) is gitignored, not committed -- it's rebuilt by CI
on every push, not carried in the repo history.
"""

import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = Path(__file__).resolve().parent / "site"

# So `import aat` below works no matter what directory this script is
# invoked from.
sys.path.insert(0, str(REPO_ROOT))

try:
    import pdoc
    import pdoc.render
except ImportError:
    sys.exit(
        "pdoc is required to build the API docs but isn't installed.\n"
        "Install it with: pip install pdoc --break-system-packages"
    )

import aat  # noqa: E402  (confirms aat.core itself imports cleanly before we start)


def build():
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)

    pdoc.render.configure(
        docformat="google",
        footer_text=(
            "aat public API -- generated by docs/build_docs.py from the "
            "package's own docstrings; do not edit by hand."
        ),
        search=True,
        math=False,
        mermaid=False,
    )

    # aat.core has no dependency on dspy at all; aat.english does. Build
    # docs for aat/aat.core unconditionally, and only add aat.english if
    # its dependency (dspy) happens to be installed in this environment --
    # so `python docs/build_docs.py` still works for a core-only checkout.
    modules = ["aat", "aat.core"]
    try:
        import aat.english  # noqa: F401

        modules.append("aat.english")
    except ImportError as exc:
        print(f"Skipping aat.english docs -- {exc} (install the 'english' extra to include it)")

    pdoc.pdoc(*modules, output_directory=OUTPUT_DIR)
    print(f"Wrote docs to {OUTPUT_DIR}")


if __name__ == "__main__":
    build()
